name: java_workflow
on:
 push:
  branches:
    - master
jobs:
  jods1:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4.2.2
      - name: install java
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '17'
         cache: maven
      - name: install
        run: mvn clean install package
